version: '3.1'

services:
  www:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - /mnt/Home/git/00-WebPyotrAntropov/www:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=pyotrantropov.com,www.pyotrantropov.com
      - LETSENCRYPT_HOST=pyotrantropov.com,www.pyotrantropov.com
      - LETSENCRYPT_EMAIL=pyotr@pyotrantropov.com

# docker run --detach \
#     --name nginx-proxy \
#     --network 00-webpyotrantropov_default \
#     --publish 80:80 \
#     --publish 443:443 \
#     --volume certs:/etc/nginx/certs \
#     --volume vhost:/etc/nginx/vhost.d \
#     --volume html:/usr/share/nginx/html \
#     --volume /var/run/docker.sock:/tmp/docker.sock:ro \
#     nginxproxy/nginx-proxy

# docker run --detach \
#     --name nginx-proxy-acme \
#     --network 00-webpyotrantropov_default \
#     --volumes-from nginx-proxy \
#     --volume /var/run/docker.sock:/var/run/docker.sock:ro \
#     --volume acme:/etc/acme.sh \
#     --env "DEFAULT_EMAIL=pyotr@pyotrantropov.net" \
#     nginxproxy/acme-companion