version: '3'

services:
  wordpress_db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:latest
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - "3306"
      - "33060"

  wordpress:
    image: wordpress:latest
    ports:
      - "80"
    volumes:
      - wp_data:/var/www/html
    restart: always
    hostname: pyotrantropov.duckdns.org
    environment:
      - VIRTUAL_HOST=pyotrantropov.duckdns.org
      - LETSENCRYPT_HOST=pyotrantropov.duckdns.org
      - LETSENCRYPT_EMAIL=pyotr@pyotrantropov.duckdns.org
      - WORDPRESS_DB_HOST=wordpress_db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress

  # www:
  #   image: nginx:alpine
  #   container_name: nginx-www
  #   restart: always
  #   expose:
  #     - "80"
  #   volumes:
  #     - /mnt/Home/git/00-WebPyotrAntropov/www:/usr/share/nginx/html:ro
  #   environment:
  #     - VIRTUAL_HOST=pyotrantropov.duckdns.org
  #     - LETSENCRYPT_HOST=pyotrantropov.duckdns.org
  #     - LETSENCRYPT_EMAIL=pyotr@pyotrantropov.duckdns.org

  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro

  docker-gen:
    image: nginxproxy/docker-gen
    container_name: nginx-proxy-gen
    restart: always
    command: -notify-sighup nginx-proxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx-proxy
    volumes:
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen"

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    restart: always
    environment:
      - DEFAULT_EMAIL=pyotrantropov.duckdns.org
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro



volumes:
  conf:
  vhost:
  html:
  certs:
  acme:
  wp_data:
  db_data:
