version: '2'

services:
  www:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - /mnt/Home/git/00-WebPyotrAntropov/www:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=pyotrantropov.ddns.net,www.pyotrantropov.ddns.net
      - LETSENCRYPT_HOST=pyotrantropov.ddns.net,www.pyotrantropov.ddns.net
      - LETSENCRYPT_EMAIL=pyotr@pyotrantropov.ddns.net